### ISSUE TITLE
please port to cmake

### ISSUE THREAD

**Issue by gonsie** [LLNL/lwgrp#2]
I cannot build this using spack on Sierra-like platforms because it doesn't know ppc64le.

**Comment by hjelmn** [comment]
Just run autoreconf -ivf.  Autotools can handle ppc64le just fine :)

**Comment by gonsie** [comment]
I am trying to build lwgrp via spack. So the either spack needs to do some magic, or fix the spack package for this, or fix config.guess that is checked into this repo.

**Comment by hjelmn** [comment]
Fixing config.guess should be as simple as running autoreconf with three latest autotools (which should be on the target system). It will update all the generated configure files (including config.guess). Those generated files really shouldn't be in any repo though. Only the release tarballs.

**Comment by hjelmn** [comment]
If spack is checking out this repo from git the spack package needs to run autoreconf -ivf ; configure.  There really should be a release tarball though as mentioned in another bug.

**Comment by becker33** [comment]
@gonsie I think your best plan here is to force autoreconf in the lwgrp spackage.

**Comment by gonsie** [comment]
My bad. The real issue was in the DTCMP spackage, not this one. This is why you shouldn't file issues at the end of the day.
